token: bot118760525:AAFcwJxKeF7pWce47z57NcU4ONBCzR8hDbA

// app.get('/near', function(req, res){
//     location = cinemasBot.getQueryVariable('city', req);
//     cinemasBot.getCinema(location, function(theaters){
//         console.log(theaters);
//     });
// });

// app.get('/theater', function(req, res){
//     location = cinemasBot.getQueryVariable('city', req);
//     theater = cinemasBot.getQueryVariable('theater', req);
//     getTheater(location, theater, res);
// });

// app.get('/movie', function(req, res){
//     location = cinemasBot.getQueryVariable('city', req);
//     theater = cinemasBot.getQueryVariable('theater', req);
//     movie = cinemasBot.getQueryVariable('movie', req);
//     getMovie(location, theater, movie, res);
// });